### ISSUE TITLE
Rotor Calc points/RP auto/teleop issue

### ISSUE THREAD

**Issue by bdaroz** [NicholsSchool/2017-Score-Sheet#2]
It looks like the calculations through auto are ok, capping at 2 rotors spinning, but if you get all 4 spinning do you mark 2 in auto, 2 in teleop? The points are correct then, but you miss the 4 rotor RP bonus. If you mark 2 auto 4 teleop, you get an extra 80 points, but you get the RP.

**Comment by jonkiddy** [comment]
Good point. I just saw the change in rule set. I made the update.
